CREATE DATABASE ENERGYDB2;
USE ENERGYDB2;

-- 1. country table
CREATE TABLE country (
    CID VARCHAR(10) PRIMARY KEY,
    Country VARCHAR(100) UNIQUE
);

SELECT * FROM COUNTRY;

-- 2. emission_3 table
CREATE TABLE emission_3 (
    country VARCHAR(100),
        energy_type VARCHAR(50),
    year INT,
    emission INT,
    per_capita_emission DOUBLE,
    FOREIGN KEY (country) REFERENCES country(Country)
);

SELECT * FROM EMISSION_3;


-- 3. population table
CREATE TABLE population (
    countries VARCHAR(100),
    year INT,
    Value DOUBLE,
    FOREIGN KEY (countries) REFERENCES country(Country)
);

SELECT * FROM POPULATION;

-- 4. production table
CREATE TABLE production (
    country VARCHAR(100),
    energy VARCHAR(50),
    year INT,
    production INT,
    FOREIGN KEY (country) REFERENCES country(Country)
);


SELECT * FROM PRODUCTION;

-- 5. gdp_3 table
CREATE TABLE gdp_3 (
    Country VARCHAR(100),
    year INT,
    Value DOUBLE,
    FOREIGN KEY (Country) REFERENCES country(Country)
);

SELECT * FROM GDP_3;

-- 6. consumption table
CREATE TABLE consumption (
    country VARCHAR(100),
    energy VARCHAR(50),
    year INT,
consumption INT,
    FOREIGN KEY (country) REFERENCES country(Country)
);

-- General & Comparative Analysis
-- total emission per country for the most recent year available
SELECT COUNTRY,SUM(EMISSION) AS TOTAL_EMISSION FROM EMISSION_3 
WHERE YEAR=(SELECT MAX(YEAR) FROM EMISSION_3) GROUP BY COUNTRY 
ORDER BY TOTAL_EMISSION DESC; 

-- top 5 countries by GDP in the most recent year
SELECT COUNTRY,VALUE AS GDP FROM GDP_3 WHERE 
YEAR=(SELECT MAX(YEAR) FROM EMISSION_3) 
ORDER BY GDP DESC LIMIT 5;

--  energy production and consumption by country and year
SELECT PROD.COUNTRY, PROD.YEAR, PROD.PRODUCTION, CONS.CONSUMPTION FROM PRODUCTION PROD JOIN CONSUMPTION CONS ON 
PROD.COUNTRY=CONS.COUNTRY AND PROD.YEAR=CONS.YEAR;

-- energy types that contribute most to emissions across all countries
SELECT ENERGY_TYPE, SUM(EMISSION) AS 
TOTAL_EMISSION FROM EMISSION_3 GROUP BY 
ENERGY_TYPE ORDER BY TOTAL_EMISSION DESC;

-- Trend Analysis Over Time
-- global emissions changed year over year?
SELECT YEAR,SUM(EMISSION) AS GLOBAL_EMMISION 
FROM EMISSION_3 GROUP BY YEAR ORDER BY YEAR;

-- Trend in GDP for each country over the given years
SELECT COUNTRY, YEAR, VALUE AS GDP 
FROM GDP_3 ORDER BY COUNTRY, YEAR;

-- population growth affected total emissions in each country
SELECT P.COUNTRIES, E.YEAR, SUM(E.EMISSION) AS TOTAL_EMISSION, 
ROUND(SUM(P.VALUE),2) AS POPULATION_GROWTH FROM POPULATION P 
JOIN EMISSION_3 E ON P.COUNTRIES=E.COUNTRY AND P.YEAR=E.YEAR 
GROUP BY P.COUNTRIES, E.YEAR ORDER BY P.COUNTRIES, E.YEAR;

-- energy consumption increased or decreased over the years for major economies
SELECT C.COUNTRY, C.YEAR, SUM(C.CONSUMPTION) AS ENERGY_CONSUMPTION 
FROM CONSUMPTION C JOIN GDP_3 G ON C.COUNTRY=G.COUNTRY 
AND C.YEAR=G.YEAR JOIN (SELECT COUNTRY FROM GDP_3 GROUP BY COUNTRY 
ORDER BY SUM(VALUE) DESC LIMIT 10) AS TOP_GDP ON 
C.COUNTRY = TOP_GDP.COUNTRY GROUP BY C.COUNTRY, C.YEAR ORDER BY 
SUM(G.VALUE) DESC;

-- average yearly change in emissions per capita for each country
SELECT COUNTRY, AVG(PER_CAPITA_EMISSION) AS 
AVG_YEARLY_CHANGE FROM EMISSION_3 GROUP BY COUNTRY;

-- Ratio & Per Capita Analysis
-- emission-to-GDP ratio for each country by year
SELECT E.COUNTRY, E.YEAR, SUM(E.EMISSION)/SUM(G.VALUE) AS 
EMISSION_TO_GDP_RATIO FROM EMISSION_3 E JOIN GDP_3 G ON 
E.COUNTRY=G.COUNTRY AND E.YEAR=G.YEAR GROUP BY E.COUNTRY, 
E.YEAR ORDER BY E.COUNTRY, E.YEAR;

-- energy consumption per capita for each country over the last decade
SELECT C.COUNTRY, C.YEAR, SUM(C.CONSUMPTION)/SUM(P.VALUE) AS ENERGY_CONSUMPTION_PER_CAPITA FROM CONSUMPTION C JOIN POPULATION P ON 
C.COUNTRY=P.COUNTRIES AND C.YEAR=P.YEAR WHERE C.YEAR >= YEAR(CURDATE())-10 GROUP BY C.COUNTRY, C.YEAR ORDER BY C.COUNTRY,C.YEAR;

-- energy production per capita vary across countries
SELECT PR.COUNTRY, PR.YEAR, SUM(PR.PRODUCTION)/SUM(PO.VALUE) AS ENERGY_PRODUCTION_PER_CAPITA FROM PRODUCTION PR JOIN POPULATION PO ON 
PR.COUNTRY=PO.COUNTRIES AND PR.YEAR=PO.YEAR GROUP BY PR.COUNTRY, PR.YEAR ORDER BY PR.COUNTRY, PR.YEAR;

-- highest energy consumption relative to GDP
SELECT C.COUNTRY, SUM(C.CONSUMPTION)/SUM(G.VALUE) AS 
ENERGY_CONSUMPTION_FOR_GDP FROM CONSUMPTION C JOIN GDP_3 G 
ON C.COUNTRY=G.COUNTRY AND C.YEAR=G.YEAR GROUP BY C.COUNTRY 
ORDER BY ENERGY_CONSUMPTION_FOR_GDP DESC LIMIT 10;

-- correlation between GDP growth and energy production growth
SELECT P.COUNTRY, G.VALUE AS GDP, P.PRODUCTION AS ENERGY_PRODUCTION,
ROUND((G.VALUE - LAG(G.VALUE) OVER (PARTITION BY P.COUNTRY ORDER BY P.YEAR)) / LAG(G.VALUE) OVER (PARTITION BY P.COUNTRY ORDER BY P.YEAR), 4) AS GDP_GROWTH_RATE,
ROUND((P.PRODUCTION - LAG(P.PRODUCTION) OVER (PARTITION BY P.COUNTRY ORDER BY P.YEAR)) / LAG(P.PRODUCTION) OVER (PARTITION BY P.COUNTRY ORDER BY P.YEAR), 4) AS PRODUCTION_GROWTH_RATE
FROM PRODUCTION P JOIN GDP_3 G ON P.COUNTRY = G.COUNTRY AND P.YEAR=G.YEAR;

-- Global Comparisons
-- top 10 countries by population by their emissions comparison
SELECT P.COUNTRIES AS COUNTRY, P.YEAR, P.VALUE AS 
POPULATION, SUM(E.EMISSION) AS TOTAL_EMISSIONS
FROM POPULATION P JOIN EMISSION_3 E ON 
P.COUNTRIES = E.COUNTRY AND P.YEAR = E.YEAR GROUP BY
P.COUNTRIES, P.YEAR, P.VALUE ORDER BY P.VALUE DESC
LIMIT 10;

-- Which countries have improved (reduced) their per capita emissions the most over the last decade?
SELECT * FROM (SELECT C.COUNTRY,(E1.PER_CAPITA_EMISSION)-(E2.PER_CAPITA_EMISSION) AS CHANGE_IN_PER_CAPITA_EMISSION FROM 
(SELECT COUNTRY, MAX(YEAR) AS MAX_YEAR, MIN(YEAR) AS MIN_YEAR FROM EMISSION_3 GROUP BY COUNTRY) C 
LEFT JOIN EMISSION_3 E1 ON C.COUNTRY=E1.COUNTRY AND C.MAX_YEAR=E1.YEAR
LEFT JOIN EMISSION_3 E2 ON C.COUNTRY=E2.COUNTRY AND C.MIN_YEAR=E2.YEAR) AS E
WHERE CHANGE_IN_PER_CAPITA_EMISSION!=0;

-- global share (%) of emissions by country
SELECT COUNTRY, ROUND(SUM(EMISSION)/(SELECT SUM(EMISSION)
FROM EMISSION_3 WHERE YEAR=(SELECT MAX(YEAR) FROM EMISSION_3))*100,2)
AS EMISSION_SHARE_PERCENT FROM EMISSION_3 WHERE 
YEAR=(SELECT MAX(YEAR) FROM EMISSION_3) GROUP BY COUNTRY 
ORDER BY EMISSION_SHARE_PERCENT DESC;

-- global average GDP, emission, and population by year
SELECT YEAR, ROUND(AVG(GDP), 2) AS AVG_GDP, ROUND(AVG(EMISSION), 2) 
AS AVG_EMISSION, ROUND(AVG(POPULATION), 2) AS AVG_POPULATION
FROM ( SELECT G.YEAR, G.VALUE AS GDP, E.EMISSION, P.VALUE AS POPULATION 
FROM GDP_3 G JOIN EMISSION_3 E ON G.COUNTRY = E.COUNTRY AND G.YEAR = E.YEAR
JOIN POPULATION P ON G.COUNTRY = P.COUNTRIES AND G.YEAR = P.YEAR ) T
GROUP BY YEAR ORDER BY YEAR;

